#!/bin/bash

filename=$1

# create a new file with vi
touch $filename

if [ ! -s $filename ]; then
echo "File is empty. Please add content to file before proceeding."
read -p "Do you want to add content to the file now? (y/n): " choice

if [ "$choice" = "y" ]; then
echo "Please select a text editor to add content to file:"
select text_editor in "vi" "emacs" "nano"
do
	case $text_editor in 
		vi )
			vi $filename
			break
			;;
		emacs )
			emacs $filename
			break
			;;
		nano )
			nano $filename
			break
			;;
		*)
			echo "Invalid option. Please select a valid text editor."
			esac
	done
else
		echo "Aborting script."
		exit
fi
fi


# change the execute permission for the owner of the file
chmod u+x $filename

# add the file to git
git add $filename

# prompt the user for a commit message
echo "Enter a commit message: "
read commit_message

# commit the changes to the local repository
git commit -m "$commit_message"

# push the changes to the remote repository
git push

# Task Completed
echo "Task Completed Successfully, Good Job!!!"
sleep 3
echo "Good bye $(git config user.name)"
